# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 586f7863aea55c11f2b89864f606a20b1a6b46e9db49df0c7ab3f95fe85a7be886bc3a3aab4ac30d410376cd62c23a54196612bc63a36cfdad23c7d92c9fed39

test:
  secret_key_base: 9afe0e4f67f68d8e8e9ff21c47178a4f055e513fb9fb9c6751de0eb514256ad5d0f134deb1c4ec9f6eccd8bfe99c23b55441e08a601b47df811dbbfd36e8b00f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
